name: game_of_fortune
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.1+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get:
  lottie:
  cloud_firestore: ^4.17.3
  image_picker: ^1.1.1
  intl: ^0.19.0
  permission_handler: ^11.3.1
  connectivity_plus: ^5.0.2
  firebase_auth: ^4.19.5
  firebase_storage: ^11.7.5
  fluttertoast: ^8.2.5
  get_storage: ^2.1.1
  firebase_core: ^2.31.0
  # google_mobile_ads: ^5.1.0
  video_player: 
  url_launcher: ^6.3.0
  flutter_html: ^3.0.0-beta.2
  unity_ads_plugin: ^0.3.20
  # easy_ads_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  cached_network_image: ^3.3.1
  country_code_picker: ^3.0.0
  flutter_svg: ^2.0.9
  


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/app_images
  filename: assets.dart
  field_prefix: null

