// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDg5U-ptXaZCTCGNGMshtuEuhQYZsOsuo',
    appId: '1:255816798591:web:c7981b9ebfe7e6962a8a4a',
    messagingSenderId: '255816798591',
    projectId: 'game-of-fortune-6a305',
    authDomain: 'game-of-fortune-6a305.firebaseapp.com',
    storageBucket: 'game-of-fortune-6a305.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Dayqkx4eQuhmlD0fT1rVgHLu7ZknciE',
    appId: '1:255816798591:android:c092f31a24e8fb732a8a4a',
    messagingSenderId: '255816798591',
    projectId: 'game-of-fortune-6a305',
    storageBucket: 'game-of-fortune-6a305.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRWzXTHEFEHl4_IeC0g5outGdXSnvt_Qo',
    appId: '1:255816798591:ios:184f523c6cbd8f252a8a4a',
    messagingSenderId: '255816798591',
    projectId: 'game-of-fortune-6a305',
    storageBucket: 'game-of-fortune-6a305.appspot.com',
    iosBundleId: 'com.duseca.gameOfFortune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRWzXTHEFEHl4_IeC0g5outGdXSnvt_Qo',
    appId: '1:255816798591:ios:184f523c6cbd8f252a8a4a',
    messagingSenderId: '255816798591',
    projectId: 'game-of-fortune-6a305',
    storageBucket: 'game-of-fortune-6a305.appspot.com',
    iosBundleId: 'com.duseca.gameOfFortune',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDg5U-ptXaZCTCGNGMshtuEuhQYZsOsuo',
    appId: '1:255816798591:web:95f224e0360d133c2a8a4a',
    messagingSenderId: '255816798591',
    projectId: 'game-of-fortune-6a305',
    authDomain: 'game-of-fortune-6a305.firebaseapp.com',
    storageBucket: 'game-of-fortune-6a305.appspot.com',
  );
}
